### ISSUE TITLE
请问这个已经测试了吗？

### ISSUE THREAD

**Issue by liuxi378** [Seifood/device_xiaomi_zeus-TWRP#2]
我的设备是小米12  Xiaomi MI 12 (codenamed "cupid") 不知道能不能通用呢

**Comment by Seifood** [comment]
Yes u can u just will need to change some stuff like blobs and prebuilt folder with ur kernel image.

**Comment by liuxi378** [comment]
> 是的，您可以只需要使用您的内核映像更改一些东西，例如 blob 和预建文件夹。

你好，我昨天使用你的源码在我的存储库试着编译了，但是结果失败，错误代码1

**Comment by Seifood** [comment]
Please contact me on telegram username @Droneship and send the full error
